### ISSUE TITLE
warnings about incorrect gtk.css using MJV dark

### ISSUE THREAD

**Issue by anterak13** [paullinuxthemer/Mc-OS-themes#22]
Using MJV dark, ubuntu 18.04, I get these warnings anytime I launch an app from the terminal

(nautilus:24340): Gtk-WARNING **: 00:39:58.460: Theme parsing error: gtk.css:559:1: Expected a valid selector

(nautilus:24340): Gtk-WARNING **: 00:39:58.461: Theme parsing error: gtk.css:1148:2: Expected semicolon

(nautilus:24340): Gtk-WARNING **: 00:39:58.461: Theme parsing error: gtk.css:1489:27: Expected a valid selector

(nautilus:24340): Gtk-WARNING **: 00:39:58.461: Theme parsing error: gtk.css:1618:15: 'bborder-color' is not a valid property name

(nautilus:24340): Gtk-WARNING **: 00:39:58.461: Theme parsing error: gtk.css:1622:20: Expected a valid selector

(nautilus:24340): Gtk-WARNING **: 00:39:58.461: Theme parsing error: gtk.css:1988:15: 'bborder-color' is not a valid property name

(nautilus:24340): Gtk-WARNING **: 00:39:58.463: Theme parsing error: gtk.css:4363:2: Expected semicolon

(nautilus:24340): Gtk-WARNING **: 00:39:58.464: Theme parsing error: gtk.css:4994:2: Junk at end of value for border-radius

(nautilus:24340): Gtk-WARNING **: 00:39:58.466: Theme parsing error: gtk.css:6305:26: Expected a valid selector

(nautilus:24340): Gtk-WARNING **: 00:39:58.466: Theme parsing error: gtk.css:7321:26: Expected a valid selector

(nautilus:24340): Gtk-WARNING **: 00:39:58.467: Theme parsing error: gtk.css:8201:64: Junk at end of value for background-image

(nautilus:24340): Gtk-WARNING **: 00:39:58.468: Theme parsing error: gtk.css:8820:55: Using one color stop with linear-gradient() is deprecated.

(nautilus:24340): Gtk-WARNING **: 00:39:58.468: Theme parsing error: gtk.css:8820:55: Missing closing bracket at end of linear gradient

(nautilus:24340): Gtk-WARNING **: 00:39:58.468: Theme parsing error: gtk.css:8933:19: not a number

(nautilus:24340): Gtk-WARNING **: 00:39:58.468: Theme parsing error: gtk.css:8951:15: 'bcbcbc' is not a valid color name

(nautilus:24340): Gtk-WARNING **: 00:39:58.469: Theme parsing error: gtk.css:10377:20: Not a valid image

**Comment by saravanabalagi** [comment]
Addressed the warnings in #33

**Comment by athaun** [comment]
i have this issue as well, and the link to #33 just links right back here. so is there a fix?
